// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9pBwkZSsFY2Nex8Imrkq4S6CKJ6MfcdM',
    appId: '1:774306870917:web:ea41408261581faeb8dbec',
    messagingSenderId: '774306870917',
    projectId: 'otamesi-71c58',
    authDomain: 'otamesi-71c58.firebaseapp.com',
    storageBucket: 'otamesi-71c58.appspot.com',
    measurementId: 'G-9G0V8LQCXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbbrwgIuQX9DO-la_7zSCV1I9uhL8CNqs',
    appId: '1:774306870917:android:7c6903c7b4d1c60bb8dbec',
    messagingSenderId: '774306870917',
    projectId: 'otamesi-71c58',
    storageBucket: 'otamesi-71c58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABsdDVRGyokkgtXDWws_W1h6h36nj7XB4',
    appId: '1:774306870917:ios:e99bc5e81e1d9e20b8dbec',
    messagingSenderId: '774306870917',
    projectId: 'otamesi-71c58',
    storageBucket: 'otamesi-71c58.appspot.com',
    iosClientId: '774306870917-o0q1jg4ck6aliqr9gsa1paof897i7hac.apps.googleusercontent.com',
    iosBundleId: 'otamesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABsdDVRGyokkgtXDWws_W1h6h36nj7XB4',
    appId: '1:774306870917:ios:57875b16930f1e3eb8dbec',
    messagingSenderId: '774306870917',
    projectId: 'otamesi-71c58',
    storageBucket: 'otamesi-71c58.appspot.com',
    iosClientId: '774306870917-ltaudb10lknfb1e022qgkmf46arteof2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
