// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7sVsVPWkU8sZCYmKQjX5AxXK1Qir9y10',
    appId: '1:591537151597:web:9281540bb7f359dded2964',
    messagingSenderId: '591537151597',
    projectId: 'nanzyamonzya',
    authDomain: 'nanzyamonzya.firebaseapp.com',
    storageBucket: 'nanzyamonzya.appspot.com',
    measurementId: 'G-XRF9G62J88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ZaEUDn76TfzwArCLoezBl8z7fc6jtEI',
    appId: '1:591537151597:android:05dd8cdd68e47e6eed2964',
    messagingSenderId: '591537151597',
    projectId: 'nanzyamonzya',
    storageBucket: 'nanzyamonzya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_B9uGPQKQa2jkV3HdKoUkQFPdQFVreEo',
    appId: '1:591537151597:ios:9f0921e8d76ae53ced2964',
    messagingSenderId: '591537151597',
    projectId: 'nanzyamonzya',
    storageBucket: 'nanzyamonzya.appspot.com',
    iosBundleId: 'morishita.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_B9uGPQKQa2jkV3HdKoUkQFPdQFVreEo',
    appId: '1:591537151597:ios:a4ec2a264022ec7bed2964',
    messagingSenderId: '591537151597',
    projectId: 'nanzyamonzya',
    storageBucket: 'nanzyamonzya.appspot.com',
    iosClientId: '591537151597-ia9m9co4f1dppctbhpappd2hs3ngt64a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
